server:
  port: 9090
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance: 
    hostname: localhost

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true