spring:
  profiles:
    active: development
   
server:
  port: 9101
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9090/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
  registration:
    enabled: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true